name: Bug Report
description: Create a report to help improve the action
labels: [bug]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is. What did you expect to happen?

  - type: markdown
    attributes:
      value: |
        ## Details

  - type: textarea
    id: logs
    attributes:
      label: Log
      description: Paste your full log here, it help a lot if you enable debug logging for the action.
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Config
      description: Paste your config file content here.
      render: json

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: If you have any additional information for us, use the field below. Please note, you can attach screenshots here, by dragging and dropping files in the field below.

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!