name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Make a release for release tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4

      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Small summary

            **Changes:**
            - Change 1
            - Change 2

            **Important notes:**
            Why is this important
          draft: true
          generate_release_notes: true
